### PR TITLE
proposed xwiki import changes

### PR DESCRIPTION
**Pull request by telic**
These are the changes I was talking about on the conference call today. I'd mostly done them already, so I figured it would be easier to just show you the code rather than trying to describe it all in an email 😄

### CODE REVIEW

**Comment by joeytakeda** [comment]
Most of these look good (I had made similar changes in SVN).  The only one I'm not sure about is the TLN anchors. As far as I can tell, most aren't actually line breaks; for example, in 1H4_CriticalSurvey has `<span id="tln-{$number)}"/>` after every paragraph and every list item. I think `<lb/>` should only occur in documents that are representing primary source documents, not in born digital documents. I'm inclined to get rid of them entirely and see what breaks. We really shouldn't have any tln-like elements outside of Shakespeare texts.

As well, I used @n in the anchors since there were cases where the `@xml:id`s were not unique, which I think strengthens the case for the "deleting all spans/anchors and see what breaks" solution.

**Comment by joeytakeda** [comment]
The only exception to the above that I can see are instances of internal references in documents (i.e. "see above") or in table of contents like sections in a document. So it might not be wise to get rid of them right away (although I don't think the scale of the issue is that big) so that we have a reference point for when we move the `@xml:id`s for the `<anchor/>`s to `<div/>`s or `<p>`s or whatever container element. Then, in a later transformation, get rid of all of the `<anchor/>`s we deem unnecessary. Maybe we should add a type to the xwiki anchors (i.e. `<anchor type="from_xwiki"/>`)?

**Comment by telic** [comment]
> I used @n in the anchors since there were cases where the @xml:ids were not unique

Do you remember where you noticed this? Non-unique IDs are a problem for ISE2 as well and should be fixed, not just worked around!

**Comment by telic** [comment]
I agree that we shouldn't be using TLNs in non-primary texts. Some of these *are* primary texts though, and using TLNs in them is justifiable (although they may be better called WLNs). Thus, I think we need to keep the "TLNs" that we have for now and remove those we don't want manually at a later stage when we know what's what. Transforming them now to <lb> rather than floating id or n values will help with the process of removing/renaming them later on.

**Comment by joeytakeda** [comment]
I agree that we should keep the TLNs, but I don't think they need to be
associated with `<lb/>`s unless it's certain that each <span id="tln-##"/>
does represent a line beginning.

To answer your first question, there are 6 texts that have duplicate ids:

```

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:364:43:
error: ID "tln-1400" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:362:46:
error: first occurrence of ID "tln-1400"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:442:43:
error: ID "tln-2704" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:440:46:
error: first occurrence of ID "tln-2704"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseFoxe_M.xml:85:47:
error: ID "tln-14" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseFoxe_M.xml:81:44:
error: first occurrence of ID "tln-14"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseHolinshed_John.xml:2854:45:
error: ID "tln-300" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseHolinshed_John.xml:2784:45:
error: first occurrence of ID "tln-300"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseJn_HistoricalNotes.xml:229:44:
error: ID "tln-40" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseJn_HistoricalNotes.xml:227:44:
error: first occurrence of ID "tln-40"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Oth/supp/iseOth_TextIntro.xml:51:40:
error: ID "tln-1" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Oth/supp/iseOth_TextIntro.xml:46:40:
error: first occurrence of ID "tln-1"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:308:
error: ID "tln-5" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:241:
error: first occurrence of ID "tln-5"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:603:
error: ID "tln-8" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:521:
error: first occurrence of ID "tln-8"

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:396:595:
error: ID "tln-1723" has already been defined

     [jing]
/Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:396:494:
error: first occurrence of ID "tln-1723"

```

On Wed, Oct 25, 2017 at 11:52 AM, Maxwell Terpstra <notifications@github.com

**Comment by joeytakeda** [comment]
(Edit: Commented via email, which doesn't support markdown; deleted and pasted here)

I agree that we should keep the TLNs, but I don't think they need to be associated with `<lb/>`s unless it's certain that each <span id="tln-##"/> does represent a line beginning.

To answer your first question, these are the texts with duplicate ids:

```
        [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/1H4/supp/ise1H4_GenIntro.xml:172:41: error: first occurrence of ID "tln-44"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/1H4/supp/ise1H4_GenIntro.xml:172:41: error: first occurrence of ID "tln-44"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/1H4/supp/ise1H4_GenIntro.xml:175:174: error: first occurrence of ID "tln-46"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/H5/supp/iseH5_GenIntro.xml:88:41: error: first occurrence of ID "tln-13"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:362:46: error: first occurrence of ID "tln-1400"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/JC/supp/iseLucretius_DeRerum.xml:440:46: error: first occurrence of ID "tln-2704"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseFoxe_M.xml:81:44: error: first occurrence of ID "tln-14"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseHolinshed_John.xml:2784:45: error: first occurrence of ID "tln-300"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Jn/supp/iseJn_HistoricalNotes.xml:227:44: error: first occurrence of ID "tln-40"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Oth/supp/iseOth_TextIntro.xml:46:40: error: first occurrence of ID "tln-1"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:241: error: first occurrence of ID "tln-5"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:66:521: error: first occurrence of ID "tln-8"
     [jing] /Users/joeytakeda/ise/ise2/ise-tei/xwiki/tei/Per/supp/iseWilkins_M.xml:396:494: error: first occurrence of ID "tln-1723"
```

**Comment by telic** [comment]
Okay, I've fixed the duplicate TLNs you mentioned, plus a couple others I noticed. I'll run the conversion over everything again to double-check that there aren't any we missed.

Wilkins_M never should have been in XWiki in the first place. I've removed it and restored the IML version with some fixes.

**Comment by telic** [comment]
I've also swapped the `<lb/>`'s out for `<anchor type="tln"/>` and made a few fixes and cleanup. Unless you have any more comments, I think this should be ready to merge. Thanks for your input!

**Comment by joeytakeda** [comment]
Looks good to me! Thanks for changing the `<lb/>`s! Once that's merged, I'm going to add another step to put the lemmas inline.

**Pull request merged**
